services:
    # Mysql database container
    db:
        image: mysql
        container_name: db_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: app
        networks:
            - app

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - app

    # Symfony apache project container
    symfony_apache:
        build: .
        container_name: symfony_apache
        ports:
          - "8741:80"
        volumes:
            - ./vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - app

networks:
    app:

volumes:
    db-data: