services:
    # Mysql database container
    db:
        image: mysql
        container_name: db_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - stock_network

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - stock_network

    # stock project container
    stock:
        build: .
        container_name: stock
        ports:
          - "8741:80"
        volumes:
            - ./vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - stock_network

networks:
    stock_network:

volumes:
    db-data: